class lookup:
  def __init__(self, key, title, desc, footer):
    self.key = key
    self.title = title
    self.desc = desc
    self.footer = footer

# Regex [^\x00-\x7F]

#\n \u2737
# \u20df (diamond)
# \u20de (square)

moves = [lookup(r"basicmoves",
                r"Basic Moves",
                r"View the details of a specific move by specifying it in the command (.e.g. '!st move knowthings'). When you roll a 6-, mark XP and prepare for the worst (unless the move says otherwise). \n\nAid\nClash\nVolley\nDefend\nDefy Danger\nInterfere\nKnow Things\nLet Fly\nPersuade\nSeek Insight",
                r""),
         lookup(r"aid",
                r"Aid",
                r"When you help someone who has not yet rolled, the GM picks 1:\n\n \u2737 They can accomplish more than they could alone\n \u2737 They gain advantage on their roll \n\nRegardless, you are exposed to any risk, cost, or consequence associated with their roll.",
                r""),
         lookup(r"clash",
                r"Clash",
                r"When you fight in melee or close quarters, roll +STR: on a 10+, your maneuver works as expected (deal your damage) and pick 1.\n\n \u2737 Avoid, prevent, or counter your enemy's attack\n \u2737 Strike hard and fast, for 1d6 extra damage, but suffer your enemy's attack\n\nOn a 7-9, your maneuver works, mostly (deal your damage) but you suffer your enemy's attack.",
                r""),
         lookup(r"defend",
                r"Defend",
                r"When you take up a defensive stance or jump in to protect others, roll +CON: on a 10+, hold 3 Readiness (or 4 if you bear a shield); on a 7-9, hold 1 Readiness (or 2 with a shield). Spend your Readiness 1-for-1 to:\n\n \u2737 Suffer an attack's damage/effects instead of your ward\n \u2737 Halve an attack's effect or damage\n \u2737 Draw all attention from your ward to yourself\n \u2737 Strike back at an attacker (deal your damage, with disadvantage)\n\nWhen you go on the offense, cease to focus on defense, or the threat passes, lose any Readiness that you hold.",
                r""),
         lookup(r"defydanger",
                r"Defy Danger",
                r"When danger looms, the stakes are high, and you do something chancy, check if another move applies. If not, roll...\n  ...+STR to power through or test your might\n  ... +DEX to employ speed, agility, or finesse\n  ... +CON to endure or hold steady\n  ...+INT to apply expertise or enact a clever plan\n  ...+WIS to exert willpower or rely on your senses \n  ... +CHA to charm, bluff, impress, or fit in\n\nOn a 10+, you pull it off as well as one could hope; on a 7-9, you can do it, but the GM will present a lesser success, a cost, or a consequence (and maybe a choice between them, or a chance to back down).",
                r""),
         lookup(r"interfere",
                r"Interfere",
                r"When you try to foil another PC's action and neither of you back down, roll...\n  ... +STR to power through or test your might\n  ... +DEX to employ speed, agility, or finesse\n  ... +CON to endure or hold steady\n  ...+INT to apply expertise or enact a clever plan \n  ... +WIS to exert willpower or rely on your senses \n  ... +CHA to charm, bluff, impress, or fit in\n\nOn a 10+, they pick 1 from the list below; on a 7-9, they pick 1 from the list below but you are left off balance, exposed, or otherwise vulnerable.\n \u2737Do it anyway, but with disadvantage on their (next) roll\n \u2737Relent, change course, or otherwise allow their move to be foiled",
                r""),
         lookup(r"knowthings",
                r"Know Things",
                r"""When you consult your accumulated knowledge, roll +INT: on a 10+, the GM will tell you something interesting and useful about the topic at hand; on a 7-9, the GM will tell you something interesting-it's on you to make it useful; either way the GM might ask, \"How do you know this?\" """,
                r""),
         lookup(r"letfly",
                r"Let Fly",
                r"When you launch a ranged attack, roll +DEX: on a 10+, you have a clear shot-deal your damage; on a 7-9, deal your damage but pick 1:\n \u2737 You must move or hold steady to get the shot, placing you in danger\n \u2737 Take what you can get; you have disadvantage on your damage roll\n \u2737 Deplete your ammo, marking the next status next to your weapon (don't pick this if it's thrown)",
                r""),
         lookup(r"persuade",
                r"Persuade",
                r"""(vs. NPCs):\nWhen you press or entice an NPC, say what you want them to do (or not do). If they have reason to resist, roll +CHA: on a 10+, they either do as you want or reveal the easiest way to convince them; on a 7-9, they reveal something you can do to convince them, though it'll likely be costly, tricky, or distasteful.\n\n(vs. PCs):\nWhen you press or entice a PC and they resist, ask their player: \"Could I possibly get you to do this, yes or no?\" If answer is \"No,\" let it drop.\n If the answer is \"Yes,\" you can roll +CHA: on a 10+, they mark XP if they do what you want, and if they don't, they must reveal how you could convince them; on a 7-9, they mark XP if they do what you want (but can refuse or make a counter-offer if they like).""",
                r""),
         lookup(r"seekinsight",
                r"Seek Insight",
                r"When you study a situation or person, looking to the GM for insight, roll +WIS: on a 10+, ask the GM 3 questions from the list below; on a 7-9, ask 1; either way, gain advantage on your next move that acts on the answers.\n \u2737What happened here recently?\n \u2737What is about to happen?\n \u2737What should I be on the lookout for?\n \u2737What here is useful or valuable to me?\n \u2737Who or what is really in control here?\n \u2737What here is not what it appears to be?",
                r""),


         lookup(r"specialmoves",
                r"Special Moves",
                r"View the details of a specific move by specifying it in the command (.e.g. `!st deathsdoor`)\n\nBurn Brightly\nDeath's Door\nEnd of Session",
                r""),
         lookup(r"burnbrightly",
                r"Burn Brightly",
                r"When you have enough XP to Level Up (6 + twice your current level), you may spend 2 XP after any roll to add +1 to that roll (maximum +1 per roll).",
                r""),
         lookup(r"deathsdoor",
                r"Death's Door",
                r"When you are dying, you glimpse the Last Door and the Lady of Crows (describe it). Then, roll +nothing: on a 10+, you wrest yourself back to the realm of the living-return to 1 HP but say how your brush with death has marked you; on a 7-9, the Lady waves you off-you're no longer dying but you're out of the action; on a 6-, your time has come-choose 1:\n \u2737 Make one last move as if you rolled a 12+, then step through the Last Door\n \u2737 Refuse to go; gain the Revenant or Ghost insert\n \u2737 Call on one of the Things Below by name and beseech it to intercede; gain the Thrall insert",
                r""),
         lookup(r"endofsession",
                r"End of Session",
                r"When a session ends, give an example of how you met the requirement of your drive. If you can, mark XP.\n Say how your opinion of or relationship with a PC, NPC, or group has changed. If you can, mark XP.\n Answer these questions as a group. For each 'yes', everyone marks XP.\n \u2737 Did we learn more about the world or its history?\n \u2737 Did we defeat a threat to Stonetop or the region?\n \u2737 Did we improve our standing with our neighbors?\n \u2737 Did we make a lasting improvement to Stonetop, or tangible progress towards doing so?\n\nPraise something about the session (in the fiction or around the table) that you enjoyed or appreciated.\nFinally, offer up a wish for future sessions: more __, less __, a chance to __, handling __ in a different way, etc. Wishes can be about what happens in the fiction or around the table. The GM will take notes.",
                r""),

         lookup(r"followermoves",
                r"Follower Moves",
                r"View the details of a specific move by specifying it in the command (.e.g. `!st dotheirthing`)\n\nOrder Follower\nDo Their Thing\nPay Up",
                r""),
         lookup(r"orderfollower",
                r"Order Follower",
                r"When you want a follower to do something contrary to their instinct, tags, or self-interest, roll +Loyalty: on a 10+, they do it; on a 7-9, they do it, but pick 1:\n \u2737 They have disadvantage on any roll to do it\n \u2737 They gripe about it; reduce their Loyalty by 1\n \u2737 They hesitate, drag their feet, or take their time",
                r""),
         lookup(r"dotheirthing",
                r"Do Their Thing",
                r"When a follower acts at your behest, they can make any of the basic and expedition moves. They gain advantage/disadvantage normally, and might (at the GM's discretion) get to roll for Death's Door.\n\nWhen you have a follower make a move that involves rolling +STAT, roll for them. Instead of +STAT, add +1 if they have at least one appropriate tag, or +2 if they're also exceptional. Otherwise, add +0.\n\nWhen a follower acts of their own accord, the GM will say what happens.",
                r""),
         lookup(r"payup",
                r"Pay Up",
                r"When you pay a follower's cost, increase their Loyalty by 1 (to a maximum of +2). You can't trigger this move again until you and your follower both Make Camp or until after a few weeks of downtime.",
                r""),

         lookup(r"expeditionmoves",
                r"Expedition Moves",
                r"View the details of a specific move by specifying it in the command (.e.g. '!st makecamp')\n\nChart a Course\nOutfit\nRequisition\nHave What You Need\nRecover\nForage\nKeep Company\nMake Camp\nStruggle as One\nReturn Triumphant",
                r""),
         lookup(r"chartacourse",
                r"Chart a Course",
                r"""When you wish to travel to a distant place, name or describe your destination (\"Gordin's Delve,\" \"the hagr's lair,\" or \"wherever these tracks lead\"). If the route is unclear, tell the GM how you intend to reach it. The GM will then tell you what's required, the risks, and how long it will likely take.\n\nWhen you set out on the journey, the GM will pres- ent each of the challenges one at a time-plus any surprises that you couldn't have seen coming-in whatever order makes the most sense. Address them all and reach your destination.""",
                r""),
         lookup(r"outfit",
                r"Outfit",
                r"""When you prepare for an expedition, mark as many on your Inventory insert as you wish to carry, either on specific items or in \"undefined.\" Mark up to 3 \u20df for a light load (quick and quiet), 4-6 \u20df for a normal load, or 7-9 \u20df for heavy load (noisy, loud, slow, quick to tire). Also, mark a number of \u20de in the Small items section equal to 4+Prosperity (again, on specific items or on Undefined). \nYou can select...\n \u2737 Items printed on the Inventory insert\n \u2737 Other common, mundane items\n \u2737 Any of your personal possessions\n \u2737 Special items for which you Trade & Barter\n\nTell the GM what you're bringing, and answer their questions about your gear and where you got it.""",
                r""),
         lookup(r"requisition",
                r"Requisition",
                r"When you borrow some of the steading's assets for an expedition (like the horses or a plow), roll +Fortunes: on a 10+, go ahead, but bring it back safely; on a 7-9, you'll need to do some convincing; on a 6-, don't mark XP-you can take the asset with you if you want, but if you do, reduce Fortunes by 1.",
                r""),
         lookup(r"havewhatyouneed",
                r"Have What You Need",
                r"""When you decide that you had something all along, transfer a mark (or marks) from your \"undefined\" inventory to a specific item or a slot. If you mark a slot, fill it with a common mundane item or something from your personal possessions. \n Alternately, you can expend a use of supplies to mark an additional small item/slot (\u20de). \nWhatever you produce, it must be something you could have had all along. The GM or any player can veto unreasonable items.""",
                r""),
         lookup(r"recover",
                r"Recover",
                r"When you take time to catch your breath and tend to what ails you, expend 1 use of supplies and regain HP equal to 4+Prosperity. You can't gain this benefit again until you take more damage. When you tend to a debility or a problematic wound, say how. The GM will either say that it's taken care of or tell you what else is required to do so.",
                r""),
         lookup(r"forage",
                r"Forage",
                r"When you spend a few hours seeking food in the wild, roll +WIS. In winter, you have disadvantage. On a 10+, pick 2; on a 7-9, pick 1:\n \u2737You acquire 4 provisions (1d6 uses)\n \u2737You acquire an extra 1d6 uses of provisions\n \u2737You discover something interesting or useful\n \u2737You avoid danger or risk (else,there is some)\n\nProvisions can substitute for supplies when you Make Camp, 1-for-1.",
                r""),
         lookup(r"keepcompany",
                r"Keep Company",
                r"When you spend a stretch of time together, ask the others if they want to Keep Company. If they do, take turns asking a PC or NPC one of the following.\n \u2737What do you do that's annoying/endearing?\n \u2737What do I do that you find annoying/endearing?\n \u2737Who or what seems to be on your mind?\n \u2737What do we find ourselves talking about?\n \u2737How do you/we pass the time?\n \u2737What new thing do you reveal about yourself?",
                r""),
         lookup(r"makecamp",
                r"Make Camp",
                r"When you Defy Danger as a group, establish the party's approach and each roll +STAT (per Defy Danger): on a 6-, you find yourself in a spot, the GM will describe it or ask you to; on a 7-9, you pull your weight; on a 10+, you do well enough to get someone else out of a spot, if you can tell us how.\n\nIf you roll a 6- but someone saves you, don't mark XP.",
                r""),
         lookup(r"struggleasone",
                r"Struggle as One",
                r"When you settle in to rest in an unsafe area, answer the GM's questions about your campsite. Each member of the party must consume 1 use of supplies or provisions; if you use a mess kit (requires fire & water), then 1 use can provide for up to four people.\nIf you eat and drink your fill, and get at least a few hours of sleep, pick 1.\n \u2737Regain HP equal to 1/2 your max (round up)\n \u2737Clear a debility\n\nIf your rest was particularly peaceful, comfortable, or enjoyable, you also gain advantage on your next roll.",
                r""),
         lookup(r"returntriumphant",
                r"Return Triumphant",
                r"When you return home in triumph, having saved your fellows, put down the threat, seized an opportunity, etc., increase the steading's Fortunes by 1 (to a max of +3).",
                r"")]


         # lookup(r"a",
         #        r"b",
         #        r"c",
         #        r""),
